import streamlit as st
import pandas as pd
from components.utils import load_css, render_page_header
from components.charts import create_kpi_card
from data_loader.loader import load_news_data, load_company_analytics

load_css()
render_page_header("AI Recommendation Center", "Proprietary trading signals generated by synthesizing multi-modal sentiment, supply chain graphs, and macro event timelines.")

news_df = load_news_data()
analytics_df = load_company_analytics()

# --- Real Signals Generation ---
signals = []
if not analytics_df.empty:
    # Get company name mapping
    company_map = {}
    if not news_df.empty:
        # news_df has 'Company' (which is actually ticker in some datasets, but loader mapped ticker->Company)
        # Let's map ticker from analytics to Company if available
        pass
        
    # Sort by intelligence score to get top signals
    if 'intelligence_score' in analytics_df.columns:
        analytics_df = analytics_df.sort_values(by='intelligence_score', ascending=False)
        
    # Load cluster mapping once
    cluster_map = {}
    try:
        import os
        from data_loader.loader import DATA_PATH
        ct_path = os.path.join(DATA_PATH, "clustered_topics.parquet")
        if os.path.exists(ct_path):
            ct_df = pd.read_parquet(ct_path)
            # Create mapping dict from cluster ID to topic_name
            cluster_map = ct_df.set_index('cluster')['topic_name'].to_dict()
    except Exception:
        pass
        
    for _, row in analytics_df.head(50).iterrows():
        ticker = row['ticker']
        
        # Determine signal based on real data
        bullish = row.get('Bullish', 0)
        bearish = row.get('Bearish', 0)
        
        # Use normalized scores (0-100) instead of raw aggregated sums
        risk = row.get('normalized_risk_score', 50)
        
        # Intelligence score ranges around 30-80, let's map it nicely to 0-100 for conviction
        raw_intel = row.get('intelligence_score', 50)
        conviction = min(100, max(0, int((raw_intel - 20) * 1.5)))
        
        cluster = row.get('cluster', 'N/A')
        
        # Build cluster mapping logic
        if cluster in cluster_map:
            topic_name = str(cluster_map[cluster]).title()
        else:
            topic_name = f"Cluster {cluster}"
            
        # Refined signal generation: Require substantial volume and distinct imbalance
        total_sentiment = bullish + bearish
        if total_sentiment > 0:
            bull_pct = bullish / total_sentiment
            bear_pct = bearish / total_sentiment
            
            if bull_pct > 0.65:
                signal = "STRONG BUY" if risk < 40 else "BUY"
            elif bear_pct > 0.65:
                signal = "STRONG SELL" if risk > 70 else "SELL"
            else:
                signal = "HOLD"
        else:
            signal = "HOLD"
            
        # Get a real driver text
        driver = row.get('risk_explanation', "")
        if pd.isna(driver) or not driver:
            driver = f"Driven by {bullish} bullish vs {bearish} bearish signals with a risk profile of {int(risk)}/100."
            
        signals.append({
            "Ticker": str(ticker).upper()[:5],
            "Company": str(ticker).upper(),
            "Sector": topic_name,
            "Signal": signal,
            "Conviction": conviction,
            "Driver": str(driver),
            "AI_Cluster": topic_name
        })

df = pd.DataFrame(signals) if signals else pd.DataFrame(columns=["Ticker", "Company", "Sector", "Signal", "Conviction", "Driver", "AI_Cluster"])

# --- Filters Section ---
with st.container(border=True):
    st.markdown("#### Signal Filters")
    col1, col2 = st.columns(2)
    with col1:
        signal_filter = st.selectbox(
            "Filter by AI Signal", 
            ["All", "STRONG BUY", "BUY", "HOLD", "SELL", "STRONG SELL"]
        )
    with col2:
        sectors = ["All"] + sorted(df['Sector'].unique().tolist())
        sector_filter = st.selectbox("Filter by Sector", sectors)

st.divider()

# --- Apply Filters ---
filtered_df = df.copy()
if signal_filter != "All":
    filtered_df = filtered_df[filtered_df['Signal'] == signal_filter]
if sector_filter != "All":
    filtered_df = filtered_df[filtered_df['Sector'] == sector_filter]

# --- KPI Section ---
k1, k2, k3 = st.columns(3)
with k1:
    create_kpi_card("Active Signals", str(len(filtered_df)), "In Filter", "normal")
with k2:
    if len(filtered_df) > 0:
        top_sector = filtered_df['Sector'].value_counts().index[0]
    else:
        top_sector = "None"
    create_kpi_card("Top Sector Focus", top_sector, "Most Signals", "inverse")
with k3:
    if len(filtered_df) > 0:
        avg_conviction = int(filtered_df['Conviction'].mean())
    else:
        avg_conviction = 0
    create_kpi_card("Avg AI Conviction", f"{avg_conviction}%", "Confidence Score", "normal")

st.markdown("<br>", unsafe_allow_html=True)

# --- Animated HTML Signal Feed ---
if len(filtered_df) == 0:
    st.info("No AI signals match your current filter criteria.")
else:
    # Sort by Conviction (highest first)
    filtered_df = filtered_df.sort_values(by="Conviction", ascending=False)
    
    feed_html = "<div style='display: flex; flex-direction: column; gap: 16px;'>"
    
    for _, row in filtered_df.iterrows():
        sig = row['Signal']
        
        # Color Coding Engine
        if "BUY" in sig:
            color, bg = "var(--color-bull)", "var(--bg-bull)"
        elif "SELL" in sig:
            color, bg = "#ff5252", "rgba(255, 82, 82, 0.1)"
        else:
            color, bg = "#ffbb33", "rgba(255, 187, 51, 0.1)"
            
        # Build HTML cleanly without deep indentation to avoid Markdown parsing bugs
        feed_html += f"<div class='headline-card' style='border-left: 4px solid {color}; padding: 20px; background: var(--card-bg);'>"
        
        # Header Row
        feed_html += f"<div style='display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 15px;'>"
        feed_html += f"<div style='display: flex; align-items: center; gap: 15px;'>"
        # Signal Badge
        feed_html += f"<span style='background: {bg}; color: {color}; padding: 6px 14px; border-radius: 6px; font-weight: 800; font-size: 0.95rem; border: 1px solid {color}; letter-spacing: 1px;'>{sig}</span>"
        # Ticker & Company
        feed_html += f"<div>"
        feed_html += f"<span style='font-size: 1.3rem; font-weight: 800; color: var(--text-bright); margin-right: 8px;'>{row['Ticker']}</span>"
        feed_html += f"<span style='font-size: 0.9rem; color: var(--text-primary); font-weight: 500;'>{row['Company']}</span>"
        feed_html += f"</div></div>"
        
        # Right Side (Conviction & Sector)
        feed_html += f"<div style='display: flex; flex-direction: column; align-items: flex-end; gap: 4px;'>"
        feed_html += f"<span style='color: var(--text-primary); font-size: 0.95rem; font-weight: 700;'>Conviction: <span style='color: {color};'>{row['Conviction']}%</span></span>"
        if row.get('AI_Cluster', 'N/A') != 'N/A':
            feed_html += f"<span style='color: var(--accent); font-size: 0.8rem; font-weight: 800; text-transform: uppercase;'>AI {row['AI_Cluster']}</span>"
        feed_html += f"<span style='color: var(--text-primary); font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px;'>{row['Sector']}</span>"
        feed_html += f"</div></div>"
        
        # Bottom Row (Driver)
        feed_html += f"<div style='font-size: 1.05rem; color: var(--text-bright); line-height: 1.5; font-weight: 500; border-top: 1px solid var(--border-color); padding-top: 12px; margin-top: 4px;'>"
        feed_html += f"<span style='color: var(--text-primary); font-size: 0.85rem; text-transform: uppercase; font-weight: 700; margin-right: 8px;'>AI Driver:</span>"
        feed_html += f"{row['Driver']}"
        feed_html += f"</div></div>"
        
    feed_html += "</div>"
    st.markdown(feed_html, unsafe_allow_html=True)
