import streamlit as st
import pandas as pd
from components.utils import load_css, render_page_header
from components.charts import create_kpi_card

load_css()

render_page_header("AI Recommendation Center", "Proprietary trading signals generated by synthesizing multi-modal sentiment, supply chain graphs, and macro event timelines.")

# --- Mock Database ---
mock_signals = [
    {"Ticker": "NVDA", "Company": "NVIDIA Corp.", "Sector": "Technology", "Signal": "STRONG BUY", "Conviction": 98, "Driver": "Unprecedented data center demand and aggressive pricing power on next-gen Blackwell chips."},
    {"Ticker": "MSFT", "Company": "Microsoft Corp.", "Sector": "Technology", "Signal": "BUY", "Conviction": 89, "Driver": "Accelerated Azure AI adoption and strong enterprise software margins."},
    {"Ticker": "AMZN", "Company": "Amazon.com Inc.", "Sector": "Consumer", "Signal": "BUY", "Conviction": 85, "Driver": "AWS growth stabilization and significant retail logistics efficiency gains."},
    {"Ticker": "AAPL", "Company": "Apple Inc.", "Sector": "Technology", "Signal": "HOLD", "Conviction": 65, "Driver": "Strong services revenue offset by slowing hardware upgrade cycles in Asia."},
    {"Ticker": "JPM", "Company": "JPMorgan Chase", "Sector": "Financials", "Signal": "BUY", "Conviction": 82, "Driver": "Net interest income resilience and robust investment banking pipeline."},
    {"Ticker": "XOM", "Company": "Exxon Mobil", "Sector": "Energy", "Signal": "HOLD", "Conviction": 60, "Driver": "Stable dividend yield balanced against softening global macroeconomic demand."},
    {"Ticker": "TSLA", "Company": "Tesla Inc.", "Sector": "Consumer", "Signal": "SELL", "Conviction": 75, "Driver": "Continued margin compression from global EV price wars and delayed product rollouts."},
    {"Ticker": "AMD", "Company": "Advanced Micro Devices", "Sector": "Technology", "Signal": "BUY", "Conviction": 81, "Driver": "Taking market share in server CPU space and launching competitive AI accelerators."},
    {"Ticker": "GOOGL", "Company": "Alphabet Inc.", "Sector": "Technology", "Signal": "HOLD", "Conviction": 55, "Driver": "Search dominance threatened by generative AI shifts; high capital expenditures."},
    {"Ticker": "META", "Company": "Meta Platforms", "Sector": "Technology", "Signal": "STRONG BUY", "Conviction": 92, "Driver": "AI-driven ad targeting improvements and aggressive cost-cutting measures."},
    {"Ticker": "BA", "Company": "Boeing Co.", "Sector": "Industrials", "Signal": "STRONG SELL", "Conviction": 94, "Driver": "Severe supply chain disruptions, regulatory scrutiny, and cash flow burn."},
    {"Ticker": "DIS", "Company": "Walt Disney Co.", "Sector": "Consumer", "Signal": "HOLD", "Conviction": 58, "Driver": "Parks profitability remains strong but legacy linear TV networks continue to drag."}
]

df = pd.DataFrame(mock_signals)

# --- Filters Section ---
with st.container(border=True):
    st.markdown("#### Signal Filters")
    col1, col2 = st.columns(2)
    with col1:
        signal_filter = st.selectbox(
            "Filter by AI Signal", 
            ["All", "STRONG BUY", "BUY", "HOLD", "SELL", "STRONG SELL"]
        )
    with col2:
        sectors = ["All"] + sorted(df['Sector'].unique().tolist())
        sector_filter = st.selectbox("Filter by Sector", sectors)

st.divider()

# --- Apply Filters ---
filtered_df = df.copy()
if signal_filter != "All":
    filtered_df = filtered_df[filtered_df['Signal'] == signal_filter]
if sector_filter != "All":
    filtered_df = filtered_df[filtered_df['Sector'] == sector_filter]

# --- KPI Section ---
k1, k2, k3 = st.columns(3)
with k1:
    create_kpi_card("Active Signals", str(len(filtered_df)), "In Filter", "normal")
with k2:
    if len(filtered_df) > 0:
        top_sector = filtered_df['Sector'].value_counts().index[0]
    else:
        top_sector = "None"
    create_kpi_card("Top Sector Focus", top_sector, "Most Signals", "inverse")
with k3:
    if len(filtered_df) > 0:
        avg_conviction = int(filtered_df['Conviction'].mean())
    else:
        avg_conviction = 0
    create_kpi_card("Avg AI Conviction", f"{avg_conviction}%", "Confidence Score", "normal")

st.markdown("<br>", unsafe_allow_html=True)

# --- Animated HTML Signal Feed ---
if len(filtered_df) == 0:
    st.info("No AI signals match your current filter criteria.")
else:
    # Sort by Conviction (highest first)
    filtered_df = filtered_df.sort_values(by="Conviction", ascending=False)
    
    feed_html = "<div style='display: flex; flex-direction: column; gap: 16px;'>"
    
    for _, row in filtered_df.iterrows():
        sig = row['Signal']
        
        # Color Coding Engine
        if "BUY" in sig:
            color, bg = "var(--color-bull)", "var(--bg-bull)"
        elif "SELL" in sig:
            color, bg = "#ff5252", "rgba(255, 82, 82, 0.1)"
        else:
            color, bg = "#ffbb33", "rgba(255, 187, 51, 0.1)"
            
        # Build HTML cleanly without deep indentation to avoid Markdown parsing bugs
        feed_html += f"<div class='headline-card' style='border-left: 4px solid {color}; padding: 20px; background: var(--card-bg);'>"
        
        # Header Row
        feed_html += f"<div style='display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 15px;'>"
        feed_html += f"<div style='display: flex; align-items: center; gap: 15px;'>"
        # Signal Badge
        feed_html += f"<span style='background: {bg}; color: {color}; padding: 6px 14px; border-radius: 6px; font-weight: 800; font-size: 0.95rem; border: 1px solid {color}; letter-spacing: 1px;'>{sig}</span>"
        # Ticker & Company
        feed_html += f"<div>"
        feed_html += f"<span style='font-size: 1.3rem; font-weight: 800; color: var(--text-bright); margin-right: 8px;'>{row['Ticker']}</span>"
        feed_html += f"<span style='font-size: 0.9rem; color: var(--text-primary); font-weight: 500;'>{row['Company']}</span>"
        feed_html += f"</div></div>"
        
        # Right Side (Conviction & Sector)
        feed_html += f"<div style='display: flex; flex-direction: column; align-items: flex-end; gap: 4px;'>"
        feed_html += f"<span style='color: var(--text-primary); font-size: 0.95rem; font-weight: 700;'>Conviction: <span style='color: {color};'>{row['Conviction']}%</span></span>"
        feed_html += f"<span style='color: var(--text-primary); font-size: 0.8rem; text-transform: uppercase; letter-spacing: 0.5px;'>{row['Sector']}</span>"
        feed_html += f"</div></div>"
        
        # Bottom Row (Driver)
        feed_html += f"<div style='font-size: 1.05rem; color: var(--text-bright); line-height: 1.5; font-weight: 500; border-top: 1px solid var(--border-color); padding-top: 12px; margin-top: 4px;'>"
        feed_html += f"<span style='color: var(--text-primary); font-size: 0.85rem; text-transform: uppercase; font-weight: 700; margin-right: 8px;'>AI Driver:</span>"
        feed_html += f"{row['Driver']}"
        feed_html += f"</div></div>"
        
    feed_html += "</div>"
    st.markdown(feed_html, unsafe_allow_html=True)
